# Generated by Django 2.2.24 on 2021-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_publi',
        ),
        migrations.AddField(
            model_name='post',
            name='data_publicação',
            field=models.DateField(auto_now=True),
        ),
    ]
